inventory-app:
  build: .
  ports:
      - 3000:3000
  environment:
      MONGODB: 'mongodb://mongodb/inventory-node'
  volumes:
      - .:/usr/src/inventory-app

mongodb:
  ports:
      - 27017:27017